global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# A scrape configuration containing endpoints to scrape
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django-app'
    scrape_interval: 5s
    metrics_path: /metrics/
    static_configs:
      - targets: ['web:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'django-app:8000'

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres-exporter'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-exporter:9187'

  - job_name: 'redis-exporter'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis-exporter:9121'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']